server:
  port: 8085

jwt:
  secret:
    key: n@r@tm@|MS^2A((ess

spring:
  cloud:
    gateway:
      routes:
        - id: user-service-auth
          uri: http://localhost:8083
          predicates:
            - Path=/api/user/
            - Method=PUT,GET
          filters:
            - RewritePath=/api/user/?(?<segment>.*), /api/$\{segment}
            - JwtAuth

        - id: user-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user/?(?<segment>.*), /api/$\{segment}

